# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/master/kas/schema-kas.json
# Base YML file for all images, this includes all the common repos and configuration.
# Copyright IMDT 2026
header:
  version: 14
  includes:
    - repo: meta-qcom
      file: ci/base.yml
    - repo: meta-qcom
      file: ci/base.lock.yml


defaults:
  repos:
    branch: master

repos:
  meta-qcom:
    url: https://github.com/qualcomm-linux/meta-qcom.git
  meta-swupdate:
    url: https://github.com/sbabic/meta-swupdate.git
    # Temporary solution until poky gets updated in meta-qcom
    commit: 30b8bb07bde140ed9579395037d4cfa213178857




