# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "imdt-qcom-oss"
BBFILE_PATTERN_imdt-qcom-oss := "^${LAYERDIR}/"
BBFILE_PRIORITY_imdt-qcom-oss = "6"

LAYERDEPENDS_imdt-qcom-oss = "core"
LAYERRECOMMENDS_imdt-qcom-oss = "openembedded-layer meta-arm"
LAYERSERIES_COMPAT_imdt-qcom-oss = "whinlatter"

