TERM_MARGIN: 40
TIMEOUT: 5
SERIAL: yes

# /QCOM Linux
# protocol: efi
# path: boot():/EFI/Linux/linux-qcs8550-hdk.efi
# cmdline: root=LABEL=rootfs rw rootwait loglevel=7 earlycon
# dtb: boot():/dtb/qcs8550-hdk.dtb

/QCOM Linux
    protocol: linux
    # Path to the kernel (Use 'Image' if vmlinux fails)
    path: boot():/Image
    # Standard cmdline
    cmdline: root=PARTLABEL=rootfs rw rootwait loglevel=7 earlyprintk=ttyS0,115200
    # Use dtb_path for clarity in modern Limine
    dtb_path: boot():/dtb/sm8550-hdk.dtb
