name: Build IMDT Base Image

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/kas-build.yml
    with:
      kas-config: 'kas/default.yml'
      machine: 'imdt-8550-sbc'
      artifact-name: 'imdt-image-base'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
